### ISSUE TITLE
Error: There is not strategy performance summary tab on the page. - Optimizer shows this error when trying to run on latest version of Scalper Bot V3

### ISSUE THREAD

**Issue by Trotter268** [akumidv/tradingview-assistant-chrome-extension#151] opened 2023-09-07 11:50 UTC

**Comment by Trotter268** [comment] 2023-09-07 11:51
![image](https://github.com/akumidv/tradingview-assistant-chrome-extension/assets/144343694/112bd235-224f-4adc-99dc-20e2b6b88b28)

**Comment by GugaMan** [comment] 2023-09-07 12:25
Same error

**Comment by g001613001** [comment] 2023-09-07 13:04
@akumidv same error

**Comment by RbR010** [comment] 2023-09-07 13:10
@akumidv same error on tradingview assistant V2.8.1

**Comment by jerso88** [comment] 2023-09-07 13:46
same here

**Comment by stefantabakovq** [comment] 2023-09-07 14:12
Temporary solution - open **Performance Summary** window in the bottom, change `strategySummary: '#bottom-area div[class^="backtesting"` in selector,js. Doesn't work without the Performance Summary window opened, don't know why

**Comment by thefingersg** [comment] 2023-09-07 15:58
Having the same issue but was working fine for most of today.

**Comment by thefingersg** [comment] 2023-09-07 16:16
I think it might be a trading view issue rather than a problem with the optimiser

**Comment by B0gdan2K** [comment] 2023-09-07 16:23
> Temporary solution - open **Performance Summary** window in the bottom, change `strategySummary: '#bottom-area div[class^="backtesting"` in selector,js. Doesn't work without the Performance Summary window opened, don't know why

Not working, still no fix.

Thank you!

**Comment by Quantbrinx** [comment] 2023-09-07 17:52
getting the same error seems like a tradingview issue. So tired of these guys always doing random shit to their UI. Is anyone else having success with this temp fix?: 
> Temporary solution - open **Performance Summary** window in the bottom, change `strategySummary: '#bottom-area div[class^="backtesting"` in selector,js. Doesn't work without the Performance Summary window opened, don't know why

**Comment by B0gdan2K** [comment] 2023-09-07 19:15
> Temporary solution - open **Performance Summary** window in the bottom, change `strategySummary: '#bottom-area div[class^="backtesting"` in selector,js. Doesn't work without the Performance Summary window opened, don't know why

the correct code line shoud be: 
strategySummary: '#bottom-area div[class^="backtesting"',    right [stefantabakovq] ?
NOT  strategySummary: '#bottom-area div[class^="backtesting"`    BUT it still does not work

**Comment by stefantabakovq** [comment] 2023-09-07 19:18
You should close the div bracket, of course. Then it should work.

**Comment by kaykay33** [comment] 2023-09-07 20:10
The temporary fix is also working for me. Thanks!

@B0gdan2K 
To clarify , change in the file "selector.js":
the line: "strategySummary: '#bottom-area div[class^="backtesting"] div[class^="tabSwitcher"] > button:nth-child(2)',"

to:
strategySummary: '#bottom-area div[class^="backtesting"]',

**Comment by stefantabakovq** [comment] 2023-09-07 20:12
> @stefantabakovq Can you post a screen shot of where those details need to be changed please?

You should edit the selector.js file in content_scripts of the extension folder!

**Comment by ZatlaTN** [comment] 2023-09-07 20:37
![image](https://github.com/akumidv/tradingview-assistant-chrome-extension/assets/63630464/097bcd64-f0c5-4d1c-8080-2878c2a7a02b)
new error after change selector.js

**Comment by B0gdan2K** [comment] 2023-09-07 20:46
> The temporary fix is also working for me. Thanks!
> 
> @B0gdan2K To clarify , change in the file "selector.js": the line: "strategySummary: '#bottom-area div[class^="backtesting"] div[class^="tabSwitcher"] > button:nth-child(2)',"
> 
> to: strategySummary: '#bottom-area div[class^="backtesting"]',

Hi friends, this worked, you are great, thanks!

**Comment by ZatlaTN** [comment] 2023-09-07 20:53
> > The temporary fix is also working for me. Thanks!
> > @B0gdan2K To clarify , change in the file "selector.js": the line: "strategySummary: '#bottom-area div[class^="backtesting"] div[class^="tabSwitcher"] > button:nth-child(2)',"
> > to: strategySummary: '#bottom-area div[class^="backtesting"]',
> 
> Hi friends, this worked, you are great, thanks!

how that i use google too but still not working to me 😢

**Comment by jynoh052** [comment] 2023-09-08 00:58
> The temporary fix is also working for me. Thanks!
> 
> @B0gdan2K To clarify , change in the file "selector.js": the line: "strategySummary: '#bottom-area div[class^="backtesting"] div[class^="tabSwitcher"] > button:nth-child(2)',"
> 
> to: strategySummary: '#bottom-area div[class^="backtesting"]',

I don't know where is the selector.js. I press f12 to find the line you said, but I can't see it. (I don't know anything about Java.😥)

**Comment by g001613001** [comment] 2023-09-08 01:28
> strategySummary：'#bottom-area div[class^="backtesting"]'，

After making changes according to the tutorial, it displays "ReferenceError: SEL is not defined"

**Comment by akumidv** [comment] 2023-09-08 01:39
Hi everyone. Thank you for your issues.
I fixed and sent new version to publish in Google Web store. Until that you can use the latest version by installing it manually from repository. Direct link for this version is here https://github.com/akumidv/tradingview-assistant-chrome-extension/archive/refs/tags/v2.9.1.zip

**Comment by langjie-zhiming** [comment] 2023-09-08 06:37
I tried to import the file you provided into the extension program of Google Chrome, but the display failed

**Comment by langjie-zhiming** [comment] 2023-09-08 06:37
> Hi everyone. Thank you for your issues. I fixed and sent new version to publish in Google Web store. Until that you can use the latest version by installing it manually from repository. Direct link for this version is here https://github.com/akumidv/tradingview-assistant-chrome-extension/archive/refs/tags/v2.9.1.zip

I tried to import the file you provided into the extension program of Google Chrome, but the display failed

**Comment by langjie-zhiming** [comment] 2023-09-08 06:39
> Hi everyone. Thank you for your issues. I fixed and sent new version to publish in Google Web store. Until that you can use the latest version by installing it manually from repository. Direct link for this version is here https://github.com/akumidv/tradingview-assistant-chrome-extension/archive/refs/tags/v2.9.1.zip

I tried to import the file you provided into the extension program of Google Chrome, but the display failed

**Comment by Fatzhiming** [comment] 2023-09-08 06:44
> Hi everyone. Thank you for your issues. I fixed and sent new version to publish in Google Web store. Until that you can use the latest version by installing it manually from repository. Direct link for this version is here https://github.com/akumidv/tradingview-assistant-chrome-extension/archive/refs/tags/v2.9.1.zip

I tried to import this file into Google's plugin, but in the end, I found it unusable

**Comment by dannydanny77** [comment] 2023-09-08 06:51
Thanks to @stefantabakovq for the quick fix yesterday and, as always, to @akumidv for the tool itself and new version...

**Comment by Fatzhiming** [comment] 2023-09-08 06:54
> Hi everyone. Thank you for your issues. I fixed and sent new version to publish in Google Web store. Until that you can use the latest version by installing it manually from repository. Direct link for this version is here https://github.com/akumidv/tradingview-assistant-chrome-extension/archive/refs/tags/v2.9.1.zip

I still can't use it on my end, is it my problem?

**Comment by akumidv** [comment] 2023-09-08 07:14
The google chrome hadn't sent to me information about review extension yet. So in webstore now is previous 2.8.1 version. The main way is waiting until the new version will be published. 
Another temporary way is installing new version manually from repository. Brief instruction is in README.md in the root of repository, the link is above (also on main page in release block)

**Comment by Chesteer89** [comment] 2023-09-08 12:57
Btw, it could be fixed with 
`#bottom-area div[class^="backtesting"] div[class^="tabsContainer"] button:nth-child(2)`
too

**Comment by Sarraj1986** [comment] 2023-09-09 08:21
guys please asking your help to solve the problem , i could not find the line strategysummry. can anyone talk as a screenshot and post it her on how to be able to change the line strategysummery

**Comment by stefantabakovq** [comment] 2023-09-09 08:23
> guys please asking your help to solve the problem , i could not find the line strategysummary. can anyone take a screenshot and post it here on how to be able to change the line strategysummary

Please refer to the author's post, new version has been added to Chrome Web store you can update and the issue wil be fixed.

**Comment by Sarraj1986** [comment] 2023-09-09 08:56
thank for your prompt reply , i already deleted the extension and added it again but same issue

**Comment by cryptogp90** [comment] 2023-09-20 01:39
Same here. I'm getting the same issue

**Comment by akumidv** [comment] 2023-09-20 15:55
Without additional info it's impossible to understand what the problem is. Do you install last version from link below with original extension and not from copy of it?  https://chrome.google.com/webstore/detail/tradingview-assistant/pfbdfjaonemppanfnlmliafffahlohfg
Can you take screenshot with error and upload it there?

**Comment by cryptogp90** [comment] 2023-09-20 15:58
My bad @akumidv, I did download the one from your youtube video from 5 months ago. I did find the link and install it manually. It works perfectly now! thank you so much for all you doing

**Closed** 2023-11-15 04:13 UTC
Labels: bug, Done
