### ISSUE TITLE
tradingview change the code it does not work anymore

### ISSUE THREAD

**Issue by GithubJaimeLee** [akumidv/tradingview-assistant-chrome-extension#168] opened 2024-04-23 16:30 UTC

**Comment by VREY8989** [comment] 2024-04-23 16:44
Same issue here. TV Changed UI

**Comment by shishibuhuo** [comment] 2024-04-23 17:32
Error: The strategy report did not found.Please retry.
If the problem reproduced then it is possible that TV UI
changed. Create task on github please (check before if it
does't alredy created)

**Comment by dstorcheus** [comment] 2024-04-24 01:45
Same error, please fix

**Comment by tzutoo** [comment] 2024-04-24 05:37
Probably caused by this line in selector.js

strategyReport: '#bottom-area div.backtesting-content-wrapper > div[class^="reportContainer"] table',

**Comment by tzutoo** [comment] 2024-04-24 06:06
Here is a temporary solution. Replace the codes in selector.js:

    strategyReport: '#bottom-area > div.bottom-widgetbar-content.backtesting > div > div.widgetContainer-_qqQIz_4 > div > div > div > table',
    strategyReportHeader: '#bottom-area > div.bottom-widgetbar-content.backtesting > div > div.widgetContainer-_qqQIz_4 > div > div > div > table > thead > tr > th',
    strategyReportRow: '#bottom-area > div.bottom-widgetbar-content.backtesting > div > div.widgetContainer-_qqQIz_4 > div > div > div > table > tbody > tr',

**Comment by ppdajianguo** [comment] 2024-04-24 08:47
<img width="506" alt="截屏2024-04-24 16 46 16" src="https://github.com/akumidv/tradingview-assistant-chrome-extension/assets/14273713/7bf63c16-ded3-4743-a22c-637bcb0b76bf">
the same error

**Comment by ppdajianguo** [comment] 2024-04-24 09:16
> > > Here is a temporary solution. Replace the codes in selector.js:
> > > ```
> > > strategyReport: '#bottom-area > div.bottom-widgetbar-content.backtesting > div > div.widgetContainer-_qqQIz_4 > div > div > div > table',
> > > strategyReportHeader: '#bottom-area > div.bottom-widgetbar-content.backtesting > div > div.widgetContainer-_qqQIz_4 > div > div > div > table > thead > tr > th',
> > > strategyReportRow: '#bottom-area > div.bottom-widgetbar-content.backtesting > div > div.widgetContainer-_qqQIz_4 > div > div > div > table > tbody > tr',
> > > ```
> > 
> > 
> > Thanks for that anyways but replacing these 3 lines didn't work for me unfortunately...
> 
> You're welcome! I've made some adjustments to the CSS selector, hope it can solve the issue.
> 
> ```
> strategyReport: '#bottom-area > div.bottom-widgetbar-content.backtesting > div > div[class*="widgetContainer"] > div > div > div > table',
>     strategyReportHeader: '#bottom-area > div.bottom-widgetbar-content.backtesting > div > div[class*="widgetContainer"] > div > div > div > table > thead > tr > th',
> strategyReportRow: '#bottom-area > div.bottom-widgetbar-content.backtesting > div > div[class*="widgetContainer"] > div > div > div > table > tbody > tr',
> ```

Thank you for your response. I will give it a try

**Comment by dannydanny77** [comment] 2024-04-24 09:31
> > > Here is a temporary solution. Replace the codes in selector.js:
> > > ```
> > > strategyReport: '#bottom-area > div.bottom-widgetbar-content.backtesting > div > div.widgetContainer-_qqQIz_4 > div > div > div > table',
> > > strategyReportHeader: '#bottom-area > div.bottom-widgetbar-content.backtesting > div > div.widgetContainer-_qqQIz_4 > div > div > div > table > thead > tr > th',
> > > strategyReportRow: '#bottom-area > div.bottom-widgetbar-content.backtesting > div > div.widgetContainer-_qqQIz_4 > div > div > div > table > tbody > tr',
> > > ```
> > 
> > 
> > Thanks for that anyways but replacing these 3 lines didn't work for me unfortunately...
> 
> You're welcome! I've made some adjustments to the CSS selector, hope it can solve the issue.
> 
> ```
> strategyReport: '#bottom-area > div.bottom-widgetbar-content.backtesting > div > div[class*="widgetContainer"] > div > div > div > table',
>     strategyReportHeader: '#bottom-area > div.bottom-widgetbar-content.backtesting > div > div[class*="widgetContainer"] > div > div > div > table > thead > tr > th',
> strategyReportRow: '#bottom-area > div.bottom-widgetbar-content.backtesting > div > div[class*="widgetContainer"] > div > div > div > table > tbody > tr',
> ```

Thanks @tzutoo . That change worked for me. Replacing these 3 lines gets the extension back to work!
Appreciate your fast response...
For the ones who'll try: don't forget to remove and reinstall the extension after you make and save the changes in the file.
Cheers.

**Comment by tzutoo** [comment] 2024-04-24 09:40
> > > > Here is a temporary solution. Replace the codes in selector.js:
> > > > ```
> > > > strategyReport: '#bottom-area > div.bottom-widgetbar-content.backtesting > div > div.widgetContainer-_qqQIz_4 > div > div > div > table',
> > > > strategyReportHeader: '#bottom-area > div.bottom-widgetbar-content.backtesting > div > div.widgetContainer-_qqQIz_4 > div > div > div > table > thead > tr > th',
> > > > strategyReportRow: '#bottom-area > div.bottom-widgetbar-content.backtesting > div > div.widgetContainer-_qqQIz_4 > div > div > div > table > tbody > tr',
> > > > ```
> > > 
> > > 
> > > Thanks for that anyways but replacing these 3 lines didn't work for me unfortunately...
> > 
> > 
> > You're welcome! I've made some adjustments to the CSS selector, hope it can solve the issue.
> > ```
> > strategyReport: '#bottom-area > div.bottom-widgetbar-content.backtesting > div > div[class*="widgetContainer"] > div > div > div > table',
> >     strategyReportHeader: '#bottom-area > div.bottom-widgetbar-content.backtesting > div > div[class*="widgetContainer"] > div > div > div > table > thead > tr > th',
> > strategyReportRow: '#bottom-area > div.bottom-widgetbar-content.backtesting > div > div[class*="widgetContainer"] > div > div > div > table > tbody > tr',
> > ```
> 
> Thanks @tzutoo . That change worked for me. Replacing these 3 lines gets the extension back to work! Appreciate your fast response... For the ones who'll try: don't forget to remove and reinstall the extension after you make and save the changes in the file. Cheers.

You're welcome. Glad to hear it works!

**Comment by g001613001** [comment] 2024-04-24 09:51
> Here is a temporary solution. Replace the codes in selector.js:這是一個臨時解決方案。取代selector.js中的代碼：
> 
> ```
> strategyReport: '#bottom-area > div.bottom-widgetbar-content.backtesting > div > div.widgetContainer-_qqQIz_4 > div > div > div > table',
> strategyReportHeader: '#bottom-area > div.bottom-widgetbar-content.backtesting > div > div.widgetContainer-_qqQIz_4 > div > div > div > table > thead > tr > th',
> strategyReportRow: '#bottom-area > div.bottom-widgetbar-content.backtesting > div > div.widgetContainer-_qqQIz_4 > div > div > div > table > tbody > tr',
> ```



> > > Here is a temporary solution. Replace the codes in selector.js:
> > > ```
> > > strategyReport: '#bottom-area > div.bottom-widgetbar-content.backtesting > div > div.widgetContainer-_qqQIz_4 > div > div > div > table',
> > > strategyReportHeader: '#bottom-area > div.bottom-widgetbar-content.backtesting > div > div.widgetContainer-_qqQIz_4 > div > div > div > table > thead > tr > th',
> > > strategyReportRow: '#bottom-area > div.bottom-widgetbar-content.backtesting > div > div.widgetContainer-_qqQIz_4 > div > div > div > table > tbody > tr',
> > > ```
> > 
> > 
> > Thanks for that anyways but replacing these 3 lines didn't work for me unfortunately...
> 
> You're welcome! I've made some adjustments to the CSS selector, hope it can solve the issue.
> 
> ```
> strategyReport: '#bottom-area > div.bottom-widgetbar-content.backtesting > div > div[class*="widgetContainer"] > div > div > div > table',
>     strategyReportHeader: '#bottom-area > div.bottom-widgetbar-content.backtesting > div > div[class*="widgetContainer"] > div > div > div > table > thead > tr > th',
> strategyReportRow: '#bottom-area > div.bottom-widgetbar-content.backtesting > div > div[class*="widgetContainer"] > div > div > div > table > tbody > tr',
> ```

It's works for me, thank you!

**Comment by tzutoo** [comment] 2024-04-24 12:35
> Should version 2.9.2 work? It doesn't solve anything for me after installation.

I suggest changing the lines manually and load it into chrome and see if it works.

**Comment by GithubJaimeLee** [comment] 2024-04-24 13:14
https://chromewebstore.google.com/detail/newhorizon-optimizer/icjbokeihkhdilfokigedgpoifnagkjo👈🏻this one work！

**Comment by GithubJaimeLee** [comment] 2024-04-24 13:14
> ![2024-04-23_22h50_23](https://private-user-images.githubusercontent.com/5848005/325059593-d7f52160-65a8-4f62-9a6c-73fe0be2d886.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NjQ3MTMsIm5iZiI6MTcxMzk2NDQxMywicGF0aCI6Ii81ODQ4MDA1LzMyNTA1OTU5My1kN2Y1MjE2MC02NWE4LTRmNjItOWE2Yy03M2ZlMGJlMmQ4ODYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjRUMTMxMzMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODAxZDQzYWVmZjY4MjlhMmM5YTBjNWFkNTJmMWZjYmVkM2UzM2E1MDJmMmJiNzcyYTM1ZTk5YWIxNjg2MTMxMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CstIuAHB9ZEovIqAG4xmEqfX7zkmjg29xqa5Y5Uy_9E)
> 
> Plugin stopped working yesterday afternoon.

https://chromewebstore.google.com/detail/newhorizon-optimizer/icjbokeihkhdilfokigedgpoifnagkjo       👈🏻this one work！

**Comment by GithubJaimeLee** [comment] 2024-04-24 13:14
> <img alt="截屏2024-04-24 16 46 16" width="506" src="https://private-user-images.githubusercontent.com/14273713/325148391-7bf63c16-ded3-4743-a22c-637bcb0b76bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NjQ3MTMsIm5iZiI6MTcxMzk2NDQxMywicGF0aCI6Ii8xNDI3MzcxMy8zMjUxNDgzOTEtN2JmNjNjMTYtZGVkMy00NzQzLWEyMmMtNjM3YmNiMGI3NmJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDEzMTMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0ZjQ2M2M1YWViOGViMzY1YjYxYmYxN2Y2OGMwOTdjNDY3NDYxOTg4NmQ5OWQ3Mjg1OWJiNWE4MmVmZjYzOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I3YlNZa-I-nSdq3En93xlYKU-DNp2-91W9b6EU5NF-E"> the same error

https://chromewebstore.google.com/detail/newhorizon-optimizer/icjbokeihkhdilfokigedgpoifnagkjo       👈🏻this one work！

**Comment by GithubJaimeLee** [comment] 2024-04-24 13:15
> Same error, please fix

https://chromewebstore.google.com/detail/newhorizon-optimizer/icjbokeihkhdilfokigedgpoifnagkjo       👈🏻this one works！

**Comment by GithubJaimeLee** [comment] 2024-04-24 13:15
> > Should version 2.9.2 work? It doesn't solve anything for me after installation.
> 
> I suggest changing the lines manually and load it into chrome and see if it works.

https://chromewebstore.google.com/detail/newhorizon-optimizer/icjbokeihkhdilfokigedgpoifnagkjo       👈🏻this one works！

**Comment by RbR010** [comment] 2024-04-24 13:42
> > Should version 2.9.2 work? It doesn't solve anything for me after installation.
> 
> I suggest changing the lines manually and load it into chrome and see if it works.

Works for me, thank you!

**Comment by scheerd** [comment] 2024-04-25 17:01
> Be cautious of scam-promoting plugins.

Looks legit to me.  Anyone else tried it?

**Comment by akumidv** [comment] 2024-04-26 07:09
fixed in version 2.9.3 It can be downloaded and installed manually due version that I sent to Google Webstore review is processing now  https://github.com/akumidv/tradingview-assistant-chrome-extension/archive/refs/tags/v2.9.3.zip

If something wrong, report there please

**Comment by akumidv** [comment] 2024-04-26 07:43
The new version of extension published in webstore.

**Closed** 2024-11-27 10:00 UTC
Labels: bug, Done, review
