### ISSUE TITLE
Results in CSV are not the actual ones and Optimum settings are not applied when cycle stops (manual or auto)

### ISSUE THREAD

**Issue by 4while** [akumidv/tradingview-assistant-chrome-extension#41] opened 2022-07-08 20:15 UTC
Your script is a daily buddy.
I put him to work and i like to see what he has for me at the end of it.
Something like a puppy with a bone, i through a bone and wait if it can get me iron, silver or gold.

Before few days everything was fine.
Today i noticed that the optimum settings that the popup window report didn't applied to the strategy, when i stopped it manual or the cycle ended normally.

I said OK, no big deal, i will go and sort the csv to find them.
However when i tried to put the settings to the script, the results still didn't match with the CSV.
I used Annealing and Random improvement with Profit Factor all and Net Profit all.

I have the CSVs if you think they can help you. The strategy was the "Grab Trading System"
It has only two parameters (long and short)

**Comment by DriesVR1232** [comment] 2022-07-09 09:15
Same here, I noticed since yesterday evening that the results showing on the optimiser and csv dont match with the tradingview results. 
Result from CSV file:
![image](https://user-images.githubusercontent.com/32335909/178099653-319bb612-bb66-4955-b444-d9f0e1bb17bf.png)
Result on tradingview
![image](https://user-images.githubusercontent.com/32335909/178099665-1fe0bc8b-fbd0-4a94-ac82-729decda327a.png)

**Comment by thecao365** [comment] 2022-07-10 12:58
> 

I also got the same error when extracting data. The resulting data is incorrect.

**Comment by thecao365** [comment] 2022-07-10 12:58
> Same here, I noticed since yesterday evening that the results showing on the optimiser and csv dont match with the tradingview results. Result from CSV file: ![image](https://user-images.githubusercontent.com/32335909/178099653-319bb612-bb66-4955-b444-d9f0e1bb17bf.png) Result on tradingview ![image](https://user-images.githubusercontent.com/32335909/178099665-1fe0bc8b-fbd0-4a94-ac82-729decda327a.png)

I also got the same error when extracting data. The resulting data is incorrect.

**Comment by akumidv** [comment] 2022-07-11 11:07
I couldn't reproduce this error. Can you try with turned off another extension in your browser? Also can you try to delete and reinstall extension?
![image](https://user-images.githubusercontent.com/12490281/178251130-2f83f789-c8a4-4c10-a803-82ea2f730a8f.png)

**Comment by akumidv** [comment] 2022-07-11 11:37
I reproduced. I have the same problem on MACD. I'll check what it can be.

**Comment by akumidv** [comment] 2022-07-11 12:27
The error has fixed. Reason in tradingview changes for performance summary updating process.
You can install new version from repository or wait until version 1.10 will pass review (1-3 days)

Thank for your issue!

**Comment by akumidv** [comment] 2022-07-11 23:11
The dropdown doesn't work for you? The extension can work with dropdown, it only don't support input.sources. If there some error please describe it, I'm planning to improve block that worked with strategy parameters, so can fix.

**Comment by duocyber** [comment] 2022-07-15 05:11
![2wma-hma setting pop-up](https://user-images.githubusercontent.com/6591215/179154365-b925dc5d-ca64-4648-ba0f-a80cf99d0f9f.png)

Second to 4while.  The dropdown items are not shown in the Strategy Parameters pop-up. Even when I tool clear and restart all without csv upload. 

Now the problem is when I remove the unwanted parameters from the csv, it seems to still scroll to removed dropdown parameters (from the TV parameters pop-up when optimizing) which I can't uncheck it from pop-up.

**Comment by duocyber** [comment] 2022-07-15 05:30
![2wma-hma gettemplate-csv](https://user-images.githubusercontent.com/6591215/179156844-ce6ee59d-53ae-468e-bd46-37aaafaa8565.png)

May the problem come with the read dropdown parameters.  As I got also NaN for every dropdown params from get-template csv files.

**Comment by akumidv** [comment] 2022-07-18 07:26
Fixed in version 1.11. It uploaded to review in google store.
 There were changes in html selectors for DD. Also there was an error in strategy parameters window, so all DD do not show. Can you check from repository is it all right for you?

**Comment by duocyber** [comment] 2022-07-18 15:05
I have tested it briefly on 1.12.  The DD now work properly including get template and the uploaded CSV file. (Also to the problem of filter in Annealing Method, it looks to be good.  There got no error now, but I am still checking the result.)

**Closed** 2022-07-24 11:37 UTC
