### ISSUE TITLE
Fix for plugin "Strategy not found" 02/23/2023

### ISSUE THREAD

**Issue by stefantabakovq** [akumidv/tradingview-assistant-chrome-extension#98] opened 2023-02-23 11:01 UTC
This error is happening because of a change in the paths on TradingView's side. 

Change CSS selectors in content_scripts > selector.js to:
 `strategyTesterTab: '#bottom-area > div.bottom-widgetbar-content.backtesting'`
....
`strategyCaption: '#bottom-area div[class^="backtesting"]  [class^="strategyGroup"] div[data-strategy-title]'`

note that `data-qa-strategy-title` is now `data-strategy-title`

**Comment by kypexin** [comment] 2023-02-23 13:41
UPDATE: now it worked. 
Mystery, and many thanks for your help.

**Comment by dayu998** [comment] 2023-02-23 14:34
非常感谢！

**Comment by VincenzoUrso** [comment] 2023-02-23 23:01
how to do that?

**Comment by stefantabakovq** [comment] 2023-02-23 23:21
> how to do that?

Download files (zip), edit content _files > selector.js with the changes above, then go to 'chrome://extensions' > Load unpacked and select files folder. Remove old version first though (it will wipe your settings unfortunately)

**Comment by akumidv** [comment] 2023-02-24 04:06
The problem is fIxed in the new 2.2 version that was send to Google for review before publishing

**Closed** 2023-03-01 00:46 UTC
Labels: bug, duplicate, Done
