### ISSUE TITLE
plugin not working

### ISSUE THREAD

**Issue by dayu998** [akumidv/tradingview-assistant-chrome-extension#97] opened 2023-02-22 12:43 UTC
![image](https://user-images.githubusercontent.com/118185206/220622828-fb6c81f8-7ac7-4c84-92dd-c22d4fa75f35.png)

**Comment by dayu998** [comment] 2023-02-22 13:23
![image](https://user-images.githubusercontent.com/118185206/220632371-82e98a53-b71d-4ea3-874c-d8ee94def371.png)

**Comment by dayu998** [comment] 2023-02-22 13:23
![image](https://user-images.githubusercontent.com/118185206/220632478-68e7ed8e-0a62-4fef-899b-7dc50165c68d.png)
![image](https://user-images.githubusercontent.com/118185206/220632519-228efe66-de29-4a9b-98fb-fb253ddb808d.png)

**Comment by g001613001** [comment] 2023-02-22 15:02
I also encountered the same problem in windows and mac chrome

**Comment by Karel607** [comment] 2023-02-22 16:03
Unfortunately I have the same problem, fingers crossed for a solution soon.

**Comment by akumidv** [comment] 2023-02-23 02:46
Yeah, thanks, I reproduced this problem and will try to fix in couple of days.

**Comment by Quetzalquatl** [comment] 2023-02-23 03:05
line 19 in selector.js

strategyCaption: '#bottom-area div[class^="backtesting"] [class^="strategyGroup"] div[data-qa-strategy-title]',

change it like this and update the extension

strategyCaption: '#bottom-area div[class^="backtesting"] [class^="strategyGroup"] div[data-strategy-title]',

**Comment by godzillafire** [comment] 2023-02-23 05:16
You're a genius Quetzalquatl you figured it out!

I want to say akumidv thank you for making such an amazing plugin. Is it possible to be able to grab the backtested trades in Tradingview since it can be downloaded as a csv?

**Comment by g001613001** [comment] 2023-02-23 05:49
According to the code of this Chrome extension, the error message "Error: There is not strategy name element on page. Open correct page please" means that the "strategy name" element cannot be found on the TradingView page, which prevents the program logic from executing correctly. Possible reasons are:

The HTML structure of the TradingView page has been changed, making it impossible to correctly retrieve the "strategy name" element. You can open the TradingView page in the Chrome browser and check if the HTML structure matches the code in the extension program.

There is a problem with the logic for finding the "strategy name" element in the extension program. You can check the implementation of the searchStrategyName function in the background.js file of the extension program to ensure that the function can find the "strategy name" element correctly.

In this extension program, the searchStrategyName function searches for the "strategy name" element by querying the HTML structure of the TradingView page. If the element cannot be found, it will throw an error message "There is not strategy name element on page".

You can try to check if the TradingView page you are using matches the code in the extension program. If the HTML structure has not been changed, you may need to check the extension program code to determine if the logic for finding the element is correct. You can try adding debug statements or logs to the extension program to better understand any issues in the code.

**Comment by stefantabakovq** [comment] 2023-02-23 11:01
#98

**Comment by kypexin** [comment] 2023-02-23 13:36
> line 19 in selector.js
> 
> strategyCaption: '#bottom-area div[class^="backtesting"] [class^="strategyGroup"] div[data-qa-strategy-title]',
> 
> change it like this and update the extension
> 
> strategyCaption: '#bottom-area div[class^="backtesting"] [class^="strategyGroup"] div[data-strategy-title]',

Seems not working for me. After this change, I encounter the following error with an extension: 

Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
Context
popup/assistant.html#content-1
Stack Trace
popup/assistant.html#content-1:0 (anonymous function)

No pop-up window is shown at all on 'Test strategy' button.

**Comment by MrDenfish** [comment] 2023-02-23 23:56
Quick and easy fix. Brilliant! Thanks for the fast troubleshooting.  
Fantastic project, thanks to everyone involved.

**Comment by Pi-Rr** [comment] 2023-02-24 02:43
> line 19 in selector.js
> 
> strategyCaption: '#bottom-area div[class^="backtesting"] [class^="strategyGroup"] div[data-qa-strategy-title]',
> 
> change it like this and update the extension
> 
> strategyCaption: '#bottom-area div[class^="backtesting"] [class^="strategyGroup"] div[data-strategy-title]',

Thanks a lot for the fix that worked for godzillafire, and sorry for my total nobe question (I am not a dev), but can you indicate how to make that change? Can I change the code in selector.js locally in my browser?

**Comment by akumidv** [comment] 2023-02-24 04:06
The problem is fixed in the new 2.2 version that was send to Google for review before publishing

**Closed** 2023-03-01 00:46 UTC
Labels: bug, Done
